default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  host: localhost
  username: rails
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: freelance_development
test:
  <<: *default
  database: freelance_test

production:
  <<: *default
  database: freelance_production
  username: freelance
  password: <%= ENV['FREELANCE_DATABASE_PASSWORD'] %>
